### ISSUE TITLE
micromatch.isMatch matches * the empty string, while minimatch does not

### ISSUE THREAD

**Issue by jandockx** [micromatch/micromatch#114]
## Please describe the **minimum necessary steps** to reproduce this issue:

````
const mm = require('minimatch')
const μm = require('micromatch')

const glob3 = 'a/*/b'
const strC = 'a//b'
console.log(mm(strC, glob3)) // false
console.log(μm.isMatch(strC, glob3)) // true
````

micromatch matches * the empty string, while minimatch does not
according to (some) bash documentation, * should be [0..n], so micromatch would be right, and minimatch would be wrong

## What is happening (but shouldn't):

the difference between minimatch and micromatch is undocumented and surprising

## What should be happening instead?

the difference is important enough to be documented if this is intended.

**Comment by phated** [comment]
@jandockx what does Bash 4.3 do?

**Comment by jandockx** [comment]
[GNU/Linux Command-Line Tools Summary / Chapter 20. Mini-Guides / Wildcards](http://www.tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm) says explicitly 

> * (asterisk)
>     this can represent any number of characters (including zero, in other words, zero or more characters) […]

But I don't know whether [GNU/Linux Command-Line Tools Summary / Chapter 20. Mini-Guides / Wildcards](http://www.tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm) is authoritative. There is no real standard. Nevertheless, this is one of these cases for which documentation makes sense.

**Comment by phated** [comment]
Is that the same as https://www.gnu.org/software/bash/manual/ (linked in docs).

**Comment by jandockx** [comment]
@phated 

[3.5.8 Filename Expansion](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html#Filename-Expansion) is too opaque for me. I don't understand what is written there.

[3.5.8.1 Pattern Matching](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html#Pattern-Matching) however also says explicitly:

> *(pattern-list)
>   Matches zero or more occurrences of the given patterns.

**Comment by jonschlinkert** [comment]
> the difference between minimatch and micromatch is undocumented and surprising

We can't use minimatch as a source of truth, it fails a huge % of the micromatch and bash unit tests. 

> There is no real standard. 

This, as you point out, is what makes this difficult sometimes. I created https://github.com/micromatch/glob-spec a while ago with the intention of creating said spec, a PR or issue to kick that off would be great. 

With all of that said, from a "purist" interpretation the micromatch result is correct. 

> Nevertheless, this is one of these cases for which documentation makes sense. Especially since there is a difference with that other 'standard', minimatch.

Honestly, it's hard to document for edge cases until someone like yourself points them out to us. A PR to add that to the docs would be great.  

closing since I think micromatch is correct until this is clarified by a spec.
