### ISSUE TITLE
Regular expression from `makeRe` does not match Windows paths

### ISSUE THREAD

**Issue by thasmo** [micromatch/micromatch#118]
## What is happening (but shouldn't):
The created regular expression which is returned by `makeRe` does not match given Windows paths.

## What should be happening instead?
The created regular expression which is returned by `makeRe` should also match Windows paths.

## Code
```js
const regexp = micromatch.makeRe('**/base/icons/icon.png');
// ^(?:(?:(?:\.(?:\/|\\))(?=.))?(?:(?!\.)(?:(?!(?:\/|^)\.).)*?\/)?base\/icons\/icon\.png(?:(?:\/|\\)|$))$
```
**Proof:**
https://regex101.com/r/aevRx8/2

**Comment by thasmo** [comment]
Shouldn't every path separator regexp-pattern be more like `(?:\/|\\)`? instead of just `\/`? Do I miss something here?

**Comment by thasmo** [comment]
Even minimatch's `makeRe` does it wrong, it seems. Also see [this comment](https://github.com/isaacs/minimatch/issues/64#issuecomment-275102348).

**Comment by thasmo** [comment]
@jonschlinkert Seems like `makeRe` in micromatch 4.0 is broken again for Windows paths; is this a possibility? I tried to use various options to handle Windows paths correctly, but the generated regular expression does not match Windows paths.

**Comment by jonschlinkert** [comment]
> is this a possibility

Anything is possible with Windows paths. What's not possible is for me to tell you if you're experiencing a bug, since you didn't provide any details. Please provide as much detail as possible, including any options, the glob pattern being passed, the full file path that is being tested against, and any other information that might help me debug. Thanks!
