### ISSUE TITLE
unable to bundle micromatch to browser using webpack

### ISSUE THREAD

**Issue by amir-arad** [micromatch/micromatch#121]
## The **minimum necessary steps** to reproduce this issue:
try to bundle a file which `require`s micromatch, using webpack.
…
## What is happening (but shouldn't):
[Link](https://ci.appveyor.com/project/amir-arad/kissfs/build/1.0.53#L608)
```
ERROR in ./node_modules/snapdragon/lib/source-maps.js
Module not found: Error: Can't resolve 'fs' in '...\node_modules\snapdragon\lib'
 @ ./node_modules/snapdragon/lib/source-maps.js 3:9-22
 @ ./node_modules/snapdragon/lib/compiler.js
 @ ./node_modules/snapdragon/index.js
 @ ./node_modules/micromatch/lib/utils.js
 @ ./node_modules/micromatch/index.js
```
…

## What should be happening instead?
In my opinion, It should bundle with no dependency in nodejs API. There shouldn't be a need to use the `fs` module just to match javascript strings. 
…

**Comment by jonschlinkert** [comment]
webpack bug, report it there

**Comment by amir-arad** [comment]
I dont think this is a webpack bug. IMO the bug is that micromatch (via snapdragon) depends on nodejs API. seems easily avoidable, and a small price to pay to be browser compatible.

**Comment by jonschlinkert** [comment]
fwiw, it's an anti-pattern to write node.js modules like they're for the browser. If you can't get something to bundle for the browser, it's a problem to be solved by the bundler. That said, I understand that if you are focused on front-end dev, then that is your frame of reference and it is frustrating when this happens. 

That said, the issue is source-maps. We can externalize source map support, I''m not opposed to that. But I think it would be in 1.0 of snapdragon, which is under development. Does that sound okay?

**Comment by amir-arad** [comment]
sounds great. thanks!

**Comment by amir-arad** [comment]
reference : 
https://github.com/here-be/snapdragon/issues/7   ?

**Comment by dxinteractive** [comment]
Hi, just hit this one. I'd love to use micromatch to match globs in a browser based library, but unfortunately cannot because of the fs / path dependency. Because i'd be using micromatch in a library, I don't get to control the bundling process, and as my library is going to be advertised for browser use, it's unfair of me to expect users of my library to have to change their bundling process. So I'm keen if the source maps component of this library is externalised.

I understand that if both snapdragon and micromatch are intended to target node.js first and foremost, and not promise browser support out of the box, then that's fine.

In the mean time I'll keep looking for another glob matcher that is designed to work in browser. I like micromatch though :P

**Comment by jonschlinkert** [comment]
> but unfortunately cannot because of the fs / path dependency

webpack and browserify have solutions for this, we've explain this so many times it's getting old. Node.js modules should be node.js modules to the best of their ability. It's not this library's job to make your code work in the browser, and it never should be.

**Comment by dxinteractive** [comment]
I'm not sure I explained my point well enough. Please don't think I'm implying that micromatch *should* be made to work in browser, I'm not asking for that, just saying that if it did that would be a bonus. Like I said, if both snapdragon and micromatch are intended to target node.js first and foremost, and not promise browser support out of the box, then that's fine, and it's not this libraries job to work in browser.

I should have just said "Does this library intend to target browsers?", and the answer is obviously no from your reply.

And I know that bundlers have solutions for this, I thought I'd post because it demonstrates a situation where a potential user of your library *cannot* use a bundler to force the library to be browser ready. If I choose to put a non-browser targeted library (micromatch) as a dependency to my own browser targeted library, then I shouldn't be doing that.

**Comment by jonschlinkert** [comment]
Bundlers **_can be used_**. The fs method(s) are the only things that obviously won’t work in the browser.

**Comment by dxinteractive** [comment]
Well sure, but bundlers can be used only by the dev doing the bundling for web. If I publish a library used by that dev, then I cannot control how they do their bundling. A library is only browser ready if it has no dependencies on node.js. If my library has any nested dependency on fs, then I cannot say that my library is browser ready. Maybe thats a purely front end dev expectation, but I think it's a reasonably widespread one. If ever I've installed a library that says it's browser ready, but it wont even compile out of the box because something is pulling fs in, then it was wrong for the library to say it was browser ready in the first place. It would throw my end users down a rabbit hole of "this isnt a node.js library, why is fs even mentioned? is that deep down node.js dependency actually important or can i ignore it?".

None of this really matters anyway if micromatch is mainly aiming for node.js, or if the dev using micromatch is in control of the bundling.

**Comment by doowb** [comment]
@dxinteractive you can bundle and distribute the bundle as a "browser ready" library so your users don't have to bundle it. I'm assuming you're already doing that if you're using npm modules and `require` anyway.

**Comment by dxinteractive** [comment]
Ah, just bundle my libraries dependencies together with my library code, so the dependency doesn't need to be bundled by the end user? Yeah, that would work, thanks. @jonschlinkert I think I get your point now.
