### ISSUE TITLE
Update snapdragon to latest version

### ISSUE THREAD

**Issue by danez** [micromatch/micromatch#122]
This is here to track progress of updating snapdragon in micromatch

### Dependencies

- [x] Update snapdragon in nanomatch micromatch/nanomatch#9
- [x] Update snapdragon in expand-brackets micromatch/expand-brackets#9 => **4.0.0**
- [x] Update snapdragon and expand-brackets in extglob => **3.0.0**
- [ ] Update snapdragon, nanomatch, expand-brackets and extglob in micromatch

**Comment by wtgtybhertgeghgtwtg** [comment]
So, since `snapdragon@0.12` came out, does that mean these should be bumped to use that?

**Comment by danez** [comment]
0.12 has literally no difference to 0.11.4, so not sure why it was released in the first place (@doowb), but yes we should use the latest version then.

**Comment by doowb** [comment]
I had to rollback the changes in `0.11.4` and re-publish `0.11.3` as `0.11.5` because `0.11.4` had breaking changes due to differences in how the nodes are handled in different versions of `snapdragon-util`. This showed up in an [issue in breakdance](https://github.com/breakdance/breakdance/issues/11).

I published `0.12.0` with the newer changes from `0.11.4` so those could be used.

**Comment by bradgreens** [comment]
I believe that because `snapdragon@0.8.1` has `base@0.11.1` as dependency, which has `mixin-deep@1.2.0` as a dependency, GitHub is flagging my package-lock.json with the following security vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2018-3719.

In my use case, this comes through the `ts-loader` dependency chain.

**Comment by doowb** [comment]
Based on how [npm handles semantic versioning](https://docs.npmjs.com/getting-started/semantic-versioning), you should be getting `mixin-deep@1.3.1`. If a different version is in your `package-lock.json` file, then you should update it either by deleting the `package-lock.json`, clearing the npm cache and re-installing your dependencies, or using whatever command npm suggests, which I think is `npm update`.

**Comment by bradgreens** [comment]
Thanks,

I deleted `package-lock.json`, ran `npm cache clean --force`, `npm i`. It produced `base@0.11.2` with `mixin-deep@1.3.0`. `1.3.0` includes the vulnerability, interestingly enough `base@0.11.2` [appears to specify `mixin-deep@1.2.0`](https://github.com/base/base/blob/0.11.2/package.json#L39) regardless.

I also tried `npm update` after, no luck. We can't really do that anyways as we have many dependencies to update more granularly.

The root dependency is `"ts-loader": "^3.5.0",`. Not sure why I can't get it to bump to `1.3.1`. It's not exactly a show stopper, just wanted to get the vulnerability cleared off of GitHub for our repo.

**Comment by doowb** [comment]
> just wanted to get the vulnerability cleared off of GitHub for our repo

I understand... npm should be installing `mixing-deep@1.3.1` since that's published. I'm not sure why it's not, other than some other issue with npm caching a different version.

**Comment by fy0** [comment]
```
 ERROR  Failed to compile with 1 errors
This dependency was not found:
* fs in ./node_modules/_snapdragon@0.8.2@snapdragon/lib/source-maps.js
To install it, you can run: npm install --save fs
```

Seems incompatible with nuxt.js.

**Comment by fy0** [comment]
@doowb Thank you for your reminder, I know what happened now.
I exported micromatch to window to make a playground. But I fogot there's no `fs` inside browser.
