### ISSUE TITLE
[Question] Returning multiple search matches

### ISSUE THREAD

**Issue by chrisrzhou** [micromatch/micromatch#205]
Hi, thank you for this awesome project that I have been able to conveniently implement in my [project](https://github.com/unified-doc/unified-doc/tree/master/packages/unified-doc-search-micromatch)!

There are a few edge cases that I have not been able to solve for in my project, and I would like to confirm on a recommended approach with any relevant `micromatch` APIs.

I want to be able to use `micromatch` to return search results with offsets given a `query` string and a `content` string:

```ts
function search(content: string, query: string): Result[]

interface Result {
  start: 0;
  end: 0;
  value: string;
}
```

An example would be `content = 'some some some'` with the following behaviors (including only `value` of results for terseness).
- `query: 's'` returns `['s', 's', 's']`
- `query: 'some'` returns `['some', 'some', 'some']` (occurs three times)
- `query: 'some '` returns `['some ', 'some ']` (occurs twice)
- `query: 's*s'` returns `['some s', 'some s']` (occurs twice)

I have an implementation in this [codesandbox](https://codesandbox.io/s/modest-lamarr-3hqun?file=/src/index.js
) that seems to work for most situations but does not contain the full set of correct behaviors.  I appreciate any help and direction if the above query searching returning offset and matched value for results using a `micromatch`-compatible query can be solved canonically with `micromatch`!

**Comment by doowb** [comment]
From your `codesandbox` implementation, the `searchRe.exec` will start from the `searchRe.lastIndex`, which means that the pattern being searched on the second iteration is `'ome some'` for the `'some s'` and `'s*s'` queries.

This seems to make sense to me since, because otherwise the results would be overlapping.
It seems like this is the same with chrome's "find" function: When I do `Cmd+f` in the chrome and search for `'some s'`, only the first `'some s'` of the string `'some some some'` is highlighted.

To also prove that the `'some s'` query will find multiple occurrences, you can add another `'some'` and you'll get `['some s', 'some s']`.

**Comment by chrisrzhou** [comment]
Hey @doowb, you are absolutely right that the browser's find function seems to do this as well.  Funny that my attempt at the implementation was actually on the right direction despite me feeling that it was unintuitive.  I was expecting it would be more intuitive to get all combinations of the search matches, but that doesn't appear to be the case, even for something as formally implemented as brower's `Cmd+f`.  Thanks for pointing this out and learned something cool today!
