### ISSUE TITLE
No micromatch.makeRe(['**/*.js', '!dist']) ?

### ISSUE THREAD

**Issue by drpicox** [micromatch/micromatch#209]
It is more a question than an issue.

Although the documentation says that it is compatible with multimatch & minimatch I guess that is only in their respective functionalities, so the ability to work with multiple expressions only works in the same case of multimatch.

So, there is no:

```javascript
const compiledRe = micromatch.makeRe(['**/*.js', '!dist']);
// reuse the compiledRe bizillion times
```

right?

Thanks!

**Comment by doowb** [comment]
`multimatch` does not have a `makeRe` method, and the `minimatch.makeRe` method only accepts a single string as the glob pattern. The `micromatch.makeRe` method works the same way, so I'm not sure where you think it's not compatible.

Also, the main `micromatch` function will accept an array of glob patterns, which is also compatible with `multimatch`.

Since this is just a question, I labeled it as a question and I'll close it, but feel free to continue a discussion here.
