### ISSUE TITLE
Can't match string with leading dot

### ISSUE THREAD

**Issue by vwkd** [micromatch/micromatch#217]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

It seems that a leading dot prevents a glob from matching. For example, `./my/*/file.js` should match `./my/relative/file.js` but it doesn't.

## Please describe the **minimum necessary steps** to reproduce this issue:

```js
import micromatch from "micromatch";

const glob = `./my/*/file.js`
const isMatch = micromatch.matcher(glob);
console.log(isMatch(./my/relative/file.js`);
// logs false
```

## What is happening that shouldn't be?

Glob doesn't match string.

## What should be happening instead?

Glob should match string. It works with minimatch and also [globster.xyz](https://globster.xyz/?q=.%2Fmy%2F*%2Ffile.js&f=.%2Fmy%2Frelative%2Ffile.js).

**Comment by jonschlinkert** [comment]
Try passing a custom `format` function on the options, as follows:

```js
const micromatch = require('micromatch');

const format = input => input.replace(/^\.\//, '');

console.log(micromatch.isMatch('./my/relative/file.js', 'my/*/file.js', { format })); //=> true
console.log(micromatch.isMatch('./my/relative/file.js', './my/*/file.js', { format })); //=> true
console.log(micromatch.isMatch('./my/relative/file.js', '**/my/*/file.js', { format })); //=> true
```

The issue of leading dot slashes has been discussed a few times on this and related repositories. Since `./` is contrived and is only really used in `require()` and `import` statements, it's not a pattern that is typically found in real file system paths. The most reliable way to handle such patterns is to use `path.normalize()` or otherwise ensure that your file paths are normalized before using any matcher. Or you can use micromatch's `format` option. We decided on this approach because it seemed to be the lesser of all other evils. 

Related:

- https://github.com/micromatch/micromatch/issues/199
- https://github.com/micromatch/micromatch/issues/217

Please let me know if this helps.

**Comment by dawgwe1** [comment]
Unlink and close all old issues

**Comment by vwkd** [comment]
Thanks for the reply. Feel free to close this if this indeed works as intended. Though it would be helpful to mention this in the README so other people won't have to run into debugging this issue.

**Comment by elmpp** [comment]
```
const match = micromatch(['/a/file/path/.hiddenFile.ejs.txt', '*.ejs.*', {matchBase: true}]
```

This is awful DX

**Comment by jonschlinkert** [comment]
> This is awful DX

Yeah, I wouldn't do what you did either.

**Comment by JounQin** [comment]
> `console.log(micromatch.isMatch('./my/relative/file.js', 'my/*/file.js', { format })); //=> true`

This is not the desired behavior in our cases.
