### ISSUE TITLE
Request to resolve the CVE (CVE-2024-4067) in latest micromatch version 4.0.7

### ISSUE THREAD

**Issue by vedant-serrala** [micromatch/micromatch#263]
@es128 @paulmillr @jonschlinkert @doowb @danez 
Can you please help me out regarding the CVE (CVE-2024-4067) on latest micromatch package version 4.0.7
Links regarding the CVE:
https://nvd.nist.gov/vuln/detail/CVE-2024-4067
https://github.com/advisories/GHSA-952p-6rrq-rcjv

Waiting for your solution
Thanks

**Comment by kevinnoll** [comment]
We would be very interested in this aswell.

**Comment by paulmillr** [comment]
Resolve it and send a pull request.

The cve is kinda useless. It elevates the severity of the issue unnecessarily.

**Comment by josteink** [comment]
I agree the CVE is overstating the severity (depending on how `micromatch` is used), but it's still a bug which *will* result in all projects somehow depending on `micromatch` to be flagged insecure due to transitive dependencies.

That creates a real pain for lots of users. While I'm not going to sit here entitled and demand that unpaid FOSS maintainers comes up with a fix for that to appease non-paying users...

I would consider it premature to close this issue until the actual CVE is fixed. People will come search for this, and they may even file new bugs.

@paulmillr : I hereby humbly suggest you re-open. 😊

**Comment by paulmillr** [comment]
> That creates a real pain for lots of developers

Who creates pain for developers:

1. Security firms reporting low-severity shit
2. Automated scanners harassing devs and users about low-severity shit

This is unpaid OSS project. If you want to fix this, contribute.

**Comment by josteink** [comment]
To be clear: I'm not asking/demanding to core team makes a fix. 

I'm asking the actual item to re-opened until *someone* fixes it, and I think that's a perfectly reasonable request.
