### ISSUE TITLE
micromatch is vulnerable to Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by sharadkalya** [micromatch/micromatch#264]
Package `micromatch` is vulnerable to Regular Expression Denial of Service (ReDoS).

The vulnerability occurs in `micromatch.braces()` in `index.js` because the pattern `.*` will greedily match anything.

By passing a malicious payload, the pattern matching will keep backtracking to the input while it doesn't find the closing bracket. 

As the input size increases, the consumption time will also increase until it causes the application to hang or slow down. There was a merged fix but further testing shows the issue persists. This issue should be mitigated by using a safe pattern that won't start backtracking the regular expression due to greedy matching.

**Comment by Phoenix-Alpha** [comment]
https://github.com/advisories/GHSA-952p-6rrq-rcjv

**Comment by graingert-coef** [comment]
> Any update on the fix? When it will be resolved?

it looks like it's been fixed on the master branch: https://github.com/micromatch/micromatch/commit/a4a4dbe9a516fcb828784eec4c990ff0e51cab6f#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L448-R457 but hasn't been released yet

**Comment by martincostello** [comment]
Looks like it was fixed in 4.0.6, as that commit is tagged for 4.0.6.

Maybe the GHSA is just out-of-date and needs updating with the fix ifo.

**Comment by thaynarbo** [comment]
> Looks like it was fixed in 4.0.6, as that commit is tagged for 4.0.6.
> 
> Maybe the GHSA is just out-of-date and needs updating with the fix ifo.

Isn't the last release of micromatch on version 4.0.4?

**Comment by hauserkristof** [comment]
hey, but the so called """latest""" 4.0.7 IS vunerable, 4.0.6 is OK

**Comment by hauserkristof** [comment]
@jonschlinkert / @danez can you please create a 4.0.8 tag on the master branch and publish a new npm version?

**Comment by martincostello** [comment]
> Isn't the last release of micromatch on version 4.0.4?

According to [GitHub releases], but [not npm](https://www.npmjs.com/package/micromatch?activeTab=versions) or [the tags](https://github.com/micromatch/micromatch/tags).

**Comment by hauserkristof** [comment]
I have created a PR for GHSA to mark the v4.0.6 NOT vunerable.

https://github.com/github/advisory-database/pull/4714

**Comment by paulmillr** [comment]
it was released correctly. master breaks backwards compat.

**Comment by graingert-coef** [comment]
@paulmillr can you backport the security fix from master to v4 and release it as 4.0.8, please?

**Comment by graingert** [comment]
I can't cut the release, but I can backport the fixes

**Comment by stevorobs3** [comment]
Thanks for jumping on and fixing this regression. Any ideas on timing for having a 4.0.8 version available in the npm registry?

**Comment by hauserkristof** [comment]
I have updated a PR #266 with the backported fix:

https://github.com/micromatch/micromatch/pull/266

**Comment by jonschlinkert** [comment]
Ok, I'll do this. But I want to say something about this first, and I think you should all have an explanation. I mentioned some of this elsewhere, but I'm happy to repeat it.

Someone made this comment on a related issue:

> I'm asking this issue to re-opened until _someone_ fixes it, and I think that's a perfectly reasonable request.

IMHO, what the community should be doing is asking them to remove the bogus CVE, not helping them get away with using highly questionable practices to browbeat open source maintainers, so that Snyk or whoever created the report can get paid. The definition of what constitutes a vulnerability seems to get broader by the day, and maintainers are at their mercy. 

To be clear, it doesn't benefit me personally to *not resolve* this issue. I don't like people being frustrated with me, it sucks. Things would be much easier for me if I just resolved it and closed the issue. Not to mention, it takes me longer to reply to these messages than it would to just fix this. _But I disagree that it's a vulnerability (otherwise I would have resolved it immediately). I can't even imagine a scenario where this would be a vulnerability. It seems to me that you'd have to do this to yourself for it to happen. Regardless, I strongly dislike being forced by these reports to implement unnecessary code changes, especially when 28 million projects will be impacted, and the people who created the reports can't even give me a real world example of how exactly an end user would be able to do what they show in their examples. They don't like getting pushback, they try to trivialize my opinion and make it seem like, "but why wouldn't you just fix this anyway?!??", and thus rarely change their reports. This, IMHO, gives them an unreasonable amount of control, and the community helps that happen by just playing along, instead of actually trying to understand and investigate what's being claimed. 

Anyway, thanks for listening. I promise I will do this as soon as I get to it. Hopefully today. 

P.S. There is no reason for anyone to make additional comments on this issue, or to create additional issues or PRs to change a version in package.json.

**Comment by jayvdb** [comment]
IIUC, the CVE is due to `/\{.*\}/.test(pattern)`.  

Firstly, that is `.test()` which returns a bool , not a match object.  The test function can bail out early even if it is given a greedy pattern, as the first `}` encountered makes it true - it does not need to find the greediest pattern possible in order to return `true`.

And `.*` is not one of the regex problems mentioned on https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS

How is that going to cause exponential work?

The work will be linear to the size of the input.

**Comment by alexthunder3** [comment]
Much respect for all maintainers of public packages, you/they help all of us save some time in our daily struggle :pray: 
I hope I speak for everyone when I say we're sorry for the impatience and insistence. We're sometimes in a hurry and didn't do a proper search before, or we're just beginners, or we're just not very good at socializing. I'm sure a good part of us do understand how ridiculous some of these CVEs are, but there's plenty of us with a non-techie manager/client breathing down our necks because there are X amount of "critical" vulnerabilities in the system.. and then take out that frustration on you guys. It's not ok, but that's unfortunately the part that reaches these tickets. 
So I guess we gotta also write some endearing words every now and then, to remind each other what FOSS is all about.

Thank you for your effort and fine :ok_hand: work dear maintainers! :pray:

**Comment by jonschlinkert** [comment]
Sorry folks, I'm going to have to do this tomorrow. If one of the other maintainers wants to take care of this, I'd be happy with that too.

**Comment by hauserkristof** [comment]
Hey @jonschlinkert , thank you for the time.

Do you think #266 would be okay if merged? That is basically a backported version of the 4.0.6 fix, and CHANGELOG updates, with fixing the broken tests for macOs node 10-12-14

**Comment by paulmillr** [comment]
@alexthunder3 thank you.

To reiterate what happened:

- Checkmarkx (security vendor) reported bogus cve in april / may
- Maintainers didn’t agree the cve was real so they ignored it
- Snyk and other automated scanners start harassing users about the cve
- Users are annoyed by scanners and scary messages from all kinds of tools
- Users start messaging devs, also devs of dependent packages which use micromatch
- Hundreds, maybe thousands of hours are wasted

In the end, the situation erodes trust into automated scanners. This is “a boy who’ve cried wolf” type of situation. When useless vulnerabilities get promoted, it’s easy to lose track of something more important.

Besides automated scanners, checkmarx should also be held responsible for this waste of everyone’s time.

**Comment by vvishalnigam** [comment]
When will this be fixed, any updates?

**Comment by pchigrin** [comment]
It stops deployments with audit check, any solution? Thanks in advance.

**Comment by mind-bending-forks** [comment]
> It stops deployments with audit check, any solution? Thanks in advance.

Possible solutions?

- Make it possible for deployments to have some configuration whereby they will skip/ignore specific reported vulnerabilities that are determined to be a) invalid b) not relevant or exploitable for the given usage (which happens a lot, in my experience.)
- Give deployments a configurable vulnerability severity level, below which reported vulnerabilities are accepted. If you're happy this is a non-issue, temporarily increase the permitted severity level, until packages have picked up the new version (and take the risk that a different vulnerability below that level could be accepted and deployed/built against in the meantime.)

**Comment by kuldeep0508** [comment]
Because this we are getting problem in the npm install of a lib (K6 lib) which we have created internally for our use-cases. And we suddenly started getting `error loading from incorrect packument` 

> 130 silly packumentCache corgi:https://inner/repository/npm-repo-local/@xyz%2fk6-commons set size:596776 disposed:false
131 verbose stack Error: loading from incorrect packument
131 verbose stack     at Advisory.load (C:\Users\x\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\metavuln-calculator\lib\advisory.js:91:27)
131 verbose stack     at [calculate] (C:\Users\x\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\metavuln-calculator\lib\index.js:60:14)
131 verbose stack     at async Promise.all (index 0)
131 verbose stack     at async [init] (C:\Users\x\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:188:9)
131 verbose stack     at async AuditReport.run (C:\Users\x\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:109:7)
131 verbose stack     at async Arborist.reify (C:\Users\x\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:268:24)
131 verbose stack     at async Install.exec (C:\Users\x\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:150:5)
131 verbose stack     at async Npm.exec (C:\Users\x\AppData\Roaming\npm\node_modules\npm\lib\npm.js:207:9)
131 verbose stack     at async module.exports (C:\Users\x\AppData\Roaming\npm\node_modules\npm\lib\cli\entry.js:74:5)

**Comment by darakeon** [comment]
For anyone reading after this and before the deploy of the new version: seems like they are doing their best. If you want to follow the status of this thread to be notified in case of changes you can subscribe in the side menu.

Please don't comment this thread just asking for news.

**Comment by hauserkristof** [comment]
Pr #266 with the fix has been approved, but not yet merged

**Comment by TheCleric** [comment]
Thank you @jonschlinkert and the other maintainers for your hard work. As an open source maintainer I know how thankless of a job this is. Take your time. You owe us nothing.

**Comment by lonewolf73** [comment]
Hello here.... I encountered in my React Native project while doing npm install the same report of `ReDoS vulnerability` about micromatch.... Reading this thread I read @hauserkristof saying release `4.0.6` doesn't affect the vulnerability. 
So I _deleted_ from my _node_modules_ 's folder that micromatch folder and then, I did a _git clone_ from micromatch's master branch where then I checked in package.json it says version `4.0.6.` 
Then, after deleting `package-lock.json` and doing `npm cache clear --force` to clean whatever would be dirty and reminding npm there's still a vulnerability, I tried _npm install_ again to check if it would find the release 4.0.6 present locally but it reported still the ReDoS vulnerability on micromatch instead.... 
Does that maybe mean when doing npm install , npm doesn't care about local version present but at the release version present on npm repository instead, so it continues to report the vulnerability? Or is there a way to tell npm to ignore any version and to use local 4.0.6 release? Or is the only way to wait to new release to make npm getting rid of that vulnerability report out? 
( I am asking just because I am trying to understand if there's a trick to allow me to continue working on my project....so thanks in advance to whoever could explain me a bit... :-) )

**Comment by bendeutz** [comment]
I am not sure if i understood you correctly, but instead of dealing with local copy of micromatch, could you not just install the version you want to have via npm by using

`npm install micromatch@4.0.6 `?

**Comment by lonewolf73** [comment]
OK @hauserkristof , thanks for the clarification... I just read right now in https://github.com/advisories/GHSA-952p-6rrq-rcjv it's mentioned that "<=" which includes 4.0.7 too so it would report the vulnerability even with 4.0.7. 
So I might just take a pause from my work and wait till 4.0.8 release so I can continue with work and in the meanwhile looking at something else I am working on

**Comment by doowb** [comment]
This is fixed in #266 and v4.0.8 has been published to npm.

**Comment by clemens** [comment]
Might I suggest to also update the GitHub releases accordingly? With all the stuff that's been going on this year with OSS being infiltrated by bad actors, seeing release versions on NPM but not in the GitHub repository that's linked there might create unnecessary mistrust (especially if the last visible release is multiple numbers back).

**Comment by jayvdb** [comment]
I think @clemens is referring to https://github.com/micromatch/micromatch/releases being 4.0.4, whilst [tags](https://github.com/micromatch/micromatch/tags) is 4.0.8

**Comment by clemens** [comment]
It's generally irritating right now:

- npmjs.com says 4.0.8
- GitHub tags says 4.0.8
- GitHub releases says 4.0.4
- Last commit (= probably the very first thing most people see, since it's at the top) says 4.0.6

The last 2 things are the troublesome part: The warnings from audit tools say 4.0.7 is vulnerable, but then the 2 only things that you see on GitHub (without first going to the "tags" tab) are 4.0.4 and 4.0.6 => makes it seem like the vulnerable version isn't even released and the version that fixes it isn't released either.

**Comment by paulmillr** [comment]
I have pushed 4.0.8 to master, and moved incorrect / breaking 4.0.6 to [separate branch](https://github.com/micromatch/micromatch/tree/v4-0-6-breaking) to preserve history.

The gh release has been created.
