### ISSUE TITLE
Check if one glob encompasses another?

### ISSUE THREAD

**Issue by Avaq** [micromatch/micromatch#80]
Is the a possibility to determine whether one glob would match *all* strings matched by another? The goal is to eliminate extraneous globs in an array of patterns to run against a single string:

```js
mm.encompasses('foo/*', 'foo/bar')  === true
mm.encompasses('foo/bar', 'foo/*') === false
mm.encompasses('foo/*', 'foo/*') === true
mm.encompasses('*', 'foo/*') === true
mm.encompasses('foo/*', '*') === false
```

So that I can:

```js
eliminateExtraneousGlobs(['foo/*', 'foo/bar', '*']) === ['*']
```

**Comment by jonschlinkert** [comment]
This is intriguing, but I don't think it's something we'll do. Mostly because it's not clear that this will achieve any benefit since the processing time to reduce the globs might take longer than filtering a list. It depends on the list size and the number and complexity of globs. 

However, this is probably something that can be done using an AST created by micromatch.  See the [.create](https://github.com/micromatch/micromatch/blob/0fd6207e9caf7711020edf42504f0c4cfc63dd89/index.js#L649) and [.parse](https://github.com/micromatch/micromatch/blob/0fd6207e9caf7711020edf42504f0c4cfc63dd89/index.js#L696) methods.
