### ISSUE TITLE
options.matchBase behavior different from minimatch

### ISSUE THREAD

**Issue by litmit** [micromatch/micromatch#83]
Let see a code:
```javascript
var minim = require("minimatch"); // v3.0.3
var microm = require("micromatch"); // v2.3.11

var matchOptions = {  matchBase: true };

var fpath = 'Incl/qqq.log';
var pattern = '**/Incl/**';

console.log(minim(fpath,pattern,matchOptions)); 
// true
console.log(microm.isMatch(fpath,pattern,matchOptions));
// false
```
Who is right?
Without matchBase both engines will return true.

**Comment by jonschlinkert** [comment]
Hi, thanks for the issue. The description of the `matchBase` option is "Allow glob patterns without slashes to match a file path based on its basename".  The point is to pass a pattern that matches only the basename of a file, like `*.js`. You're passing two globstars (`**`), but the point of the option is so that you don't need to do `**`. 

Also, fwiw this code has been completely refactored on [the dev branch](https://github.com/jonschlinkert/micromatch/tree/dev).  Here are the [matchBase](https://github.com/jonschlinkert/micromatch/blob/dev/test/options.js#L75) tests so you can see how the option is used. 

> Who is right?

Bash, whenever there is a parallel feature or option. Otherwise we just need to use our best judgement.

**Comment by litmit** [comment]
> The description of the matchBase option is "Allow glob patterns without slashes to match a file path based on its basename".

You are right, but this additional feature should not change behavior of basic features like globstar matching (IMHO).

**Comment by jonschlinkert** [comment]
IMHO, the matcher should essentially do `isMatch(path.basename(filepath), pattern)`, in which case your pattern would not match, since the basename of the filepath does not match (and should not) the directory in your pattern. Why would it? If you expect it to, why use `matchBase` at all?

But this is just my opinion, I'd like to hear from others if anyone else has an opinion about it.

**Comment by es128** [comment]
Based on the decription of the option I agree with your assessment @jonschlinkert

**Comment by es128** [comment]
Well, ok, I guess it could be considered additive. The option only applies to patterns without slashes. If a pattern has a separator, `matchBase` has no effect. That would be fine, imo, but the docs should explain it explicitly. Could be useful when providing an array of patterns.

**Comment by jonschlinkert** [comment]
> Well, ok, I guess it could be considered additive.

k, meaning that a pattern with slashes should still match as it would be expected to if `matchBase` wasn't enabled?

**Comment by es128** [comment]
Yes that's what I'm saying would be an accepted perspective. It makes no sense to deliberately use `matchBase` with a pattern that has separators, so we could decide the pattern, rather than the option wins in the conflict. 

In this way `matchBase` would only create more opportunities to find a positive match, never fewer.

**Comment by jonschlinkert** [comment]
K, I was going back and forth on that. thanks

**Comment by litmit** [comment]
@jonschlinkert 

> If you expect it to, why use matchBase at all?

I'm using a glob file like .npmignore or .gitignore. It may contain patterns like  `*.js` (should match any js files at any nesting level), `folder/*.js`,  `**/dir/*.js`, `**/dir./**` and so on. Therefore i need to set option `matchBase = true` in app that allow to works for any patterns like `*.js`. But other patterns would have been working too.

**Comment by jonschlinkert** [comment]
Sorry for lack of response to your last comment, @litmit. I've been stuck on a few windows path issues with [the refactor](https://github.com/jonschlinkert/micromatch/pull/76), but I'll make sure to revisit this as soon as I get those resolved.
